---
# tasks file for baseline

- name: Load platform vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}.sledilnik.org"

# lDWlSd0aZ06dEWM7TKiqUPxRD52snRA2GVva3Qas
- name: Delete (possible old) A record for server
  community.general.cloudflare_dns:
    zone: sledilnik.org
    record: "{{ inventory_hostname }}"
    type: A
    api_token: "{{ cf_api_token }}"
    state: absent
  tags:
    - cf

# lDWlSd0aZ06dEWM7TKiqUPxRD52snRA2GVva3Qas
- name: Create A record for server
  community.general.cloudflare_dns:
    zone: sledilnik.org
    record: "{{ inventory_hostname }}"
    type: A
    value: "{{ ansible_default_ipv4.address }}"
    api_token: "{{ cf_api_token }}"
    state: present
  tags:
    - cf

- include_tasks: apt.yml

- include_tasks: pip.yml

- include_tasks: helm.yml
  when: baseline_helm_install