---
- hosts: k8s
  connection: local
  gather_facts: no
  tags: ensure-vm
  tasks:
    - name: Ensure SSH keys for access to VM
      hcloud_ssh_key:
        name: "{{ item.name }}"
        public_key: "{{ item.key }}"
        state: present
      loop: "{{ allowed_ssh_keys | flatten(levels=1) }}"
    - name: Ensure running VM for provisioning
      hcloud_server:
        name: "{{ inventory_hostname }}"
        server_type: "{{ hcloud_server_instance }}"
        image: "{{ hcloud_server_image }}"
        location: nbg1
        state: present
        ssh_keys: "{{ allowed_ssh_keys | map(attribute='name') | list }}"
    - name: Refresh inventory to ensure new instances exist in inventory
      meta: refresh_inventory

- hosts: k8s
  tags: provision
  gather_facts: no
  pre_tasks:
    - name: Wait for VM to boot
      wait_for_connection:
        delay: 5
        timeout: 120

- hosts: k8s
  tags: provision
  roles:
    - role: baseline
      tags: baseline
    - role: xanmanning.k3s
      tags: k3s
    - role: weareinteractive.ufw
      tags: firewall